version: "3.8"

services:
  api1:
    build: .
    env_file:
      - .env
    depends_on: [db]
    expose: [8081]
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "0.5GB"

  api2:
    build: .
    env_file:
      - .env
    depends_on: [db]
    expose: [8081]
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "0.5GB"

  nginx:
    image: nginx:latest
    ports:
      - "8082:8082"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on: [api1, api2]
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "0.5GB"

  db:
    image: postgres:15-alpine
    container_name: fastify_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/postgresql.conf:/etc/postgresql/postgresql.conf:ro
      - db-data:/var/lib/postgresql/data
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: "1.5GB"

volumes:
  db-data:
